server:
  port: 8088
api:
  key: 3xCv29981_Tx091dUx98_84PTx905EB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: true
  accessTokenCookieName: accessToken
  refreshTokenCookieName: refreshToken

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

member:
  message:
    send-auto: true



auth:
  token:
    key: MemberShipService20211114!@